### ISSUE TITLE
About Cluster

### ISSUE THREAD

**Issue by TimelifeCzy** [joxeankoret/cosa-nostra#5]
Hi,Joxeankoret
1. After analyzing some samples, create a cluster，but there was nothing in the cluster.
`
0.0 (1): SET NAMES utf8;
0.0 (2): SET CHARACTER SET utf8;
0.0 (3): SET character_set_connection=utf8;
/root/cosa-nostra-master/web/db.py:587: Warning: Table 'config' already exists
  out = cur.execute(query, params)
/root/cosa-nostra-master/web/db.py:587: Warning: Table 'samples' already exists
  out = cur.execute(query, params)
/root/cosa-nostra-master/web/db.py:587: Warning: Table 'clusters' already exists
  out = cur.execute(query, params)
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Finding new samples to cluster...
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Found a total 4 new sample(s) to cluster
Total of 4 sample(s) in set
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Creating phylogenetic trees...
Calculating difference matrix for 1, iteration 0 out of 16 (0 matches, 0 cache misses)
Calculating difference matrix for 9, iteration 4 out of 16 (0 matches, 3 cache misses)
Calculating difference matrix for 12, iteration 8 out of 16 (1 matches, 5 cache misses)
Calculating difference matrix for 5, iteration 12 out of 16 (3 matches, 6 cache misses)
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Creating or updating clusters...
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Done processing phylogenetic trees!
[Sat Jul 13 18:38:26 2019 95072:140385763854144] Done

`

Web show:
`
Clusters
Total of 0 cluster(s) in the database.

Clusters
No clusters yet?
`

Mysql data:
`mysql> mysql> select id,description,filename,hash,clustered,label from samples;
+-----+----------------------------------+-----------------------------------+------------------------------------------+-----------+-------+
| id  | description                      | filename                          | hash                                     | clustered | label |
+-----+----------------------------------+-----------------------------------+------------------------------------------+-----------+-------+
|   1 | Win.Malware.Smad-7007962-0       | 2019-07-02_061245.exe             | 03b38c2a02f70a324b6183c907c231e16522aa1a |         0 | NULL  |
|   2 | NULL                             | ./virustest/2019-07-02 112822.exe | 2ead6e864d1a9f38a959b95a6ca2078b5222da6b |         0 | NULL  |
|   3 | Win.Downloader.Nemucod-7012431-0 | ./virustest/2019-07-02 125344.js  | 6428b7847471452e05d927b44b2b01276dcec9b8 |         0 | NULL  |
|   4 | NULL                             | ./virustest/2019-07-02 104837.exe | 61e8a30347ae56e98425a612f77273349c92185d |         0 | NULL  |
|   5 | Win.Dropper.Fareitvb-7008400-0   | ./virustest/2019-07-02 104810.exe | cee1d5e1a5d65ca408ae8fb76a29d663573999e0 |         0 | NULL  |
|   6 | Win.Downloader.Nemucod-7012431-0 | ./virustest/2019-07-02 113646.js  | 7aea6c384e79687e8c3c40c680f2cb4296de4989 |         0 | NULL  |
|   7 | NULL                             | ./virustest/2019-07-02 125446.vbs | 26d57656840651179ec4d7b74f815c936d222e98 |         0 | NULL  |
|   8 | NULL                             | ./virustest/2019-07-02 212708.exe | 61f01089bf7d8426524f1e92b01d7f3302202b5b |         0 | NULL  |
|   9 | NULL                             | ./virustest/2019-07-02 124353.exe | 618a309b849223b1201b7d63f29e1abec55e622c |         0 | NULL  |
|  10 | NULL                             | ./virustest/2019-07-02 145504.exe | 938fae515a12c4c610dce4d6b65b962eb853bfc4 |         0 | NULL  |
|  11 | NULL                             | ./virustest/2019-07-02 114933.js  | d2a1364247ffcf024f344ad29e8e36ceb5e0a08e |         0 | NULL  |
|  12 | Win.Dropper.Avemaria-7011911-0   | ./virustest/2019-07-02 111751.exe | 2d691e5820c9531f524b31d53350b2cacbbc3f2b |         0 | NULL  |
|  13 | NULL                             | ./virustest/2019-07-01 063838.jar | 302561b3db2dfd2b5a2d4e8091fc39bf4af9dea8 |         0 | NULL  |
|  14 | Java.Trojan.Adwind-6             | ./virustest/2019-07-02 191633.jar | 9b922d402466274b8496238b35ab4a4684891c61 |         0 | NULL  |
|  15 | NULL                             | ./virustest/2019-07-02 101838.vbs | 2f2d324df840bbee14fd94d9ea56d2cf884a941c |         0 | NULL  |
|  16 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(82).vir                  | 792b3c107160bc81bda51f5fb101fa27af5703bf |         0 | NULL  |
|  17 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(93).vir                  | e9b1211d4c314a93c3a9c0f5595e9fe2a475fb77 |         0 | NULL  |
|  18 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(85).vir                  | 2a8ae27e1bc4e315c569b25dc2c25de4681b0ec1 |         0 | NULL  |
|  19 | NULL                             | ./1/Samp(44).vir                  | dbda616c6c3de6aa503a378af4a7a95b9fe67abe |         0 | NULL  |
|  20 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(74).vir                  | a6ae7da738aabe300f973c7692dfb4dabb2b906f |         0 | NULL  |
|  21 | Doc.Dropper.Agent-6995081-0      | ./1/Samp(23).vir                  | f17b6f304ada3d759de174cb4b55ee9d8515d33e |         0 | NULL  |
|  22 | Doc.Dropper.Agent-6995093-0      | ./1/Samp(39).vir                  | 7a98435303908d78d821893113931db200893799 |         0 | NULL  |
|  23 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(80).vir                  | 91bc26677775620cb5373892cf53603ba0e6d8fc |         0 | NULL  |
|  24 | Doc.Dropper.Agent-6995085-0      | ./1/Samp(92).vir                  | c2b142ce5626fdeb9d8c3f87ce19c2bab74d34fc |         0 | NULL  |
|  25 | NULL                             | ./1/Samp(90).vir                  | 74a02ef6a2cac4148ceaa607a0dc32f8aa225879 |         0 | NULL  |
|  26 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(63).vir                  | 852b9504e996cb8afdaf331b6fe7100c43a77d8c |         0 | NULL  |
|  27 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(27).vir                  | ff27c442d883464ce7c79bb470a7aa2470f7ccee |         0 | NULL  |
|  28 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(24).vir                  | 323e2df76541edc2164c65af94e036d185e3166b |         0 | NULL  |
|  29 | Doc.Dropper.Agent-6995087-0      | ./1/Samp(62).vir                  | b0133f5171315d213f5be2976ca80d321fe6425b |         0 | NULL  |
|  30 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(3).vir                   | f1aa9ef546ce48ea11784dea9813ecf4feba3acc |         0 | NULL  |
|  31 | Doc.Dropper.Agent-6995074-0      | ./1/Samp(61).vir                  | c1030da5e3fe2d52807b251d2561803bd57fed9c |         0 | NULL  |
|  32 | Doc.Dropper.Agent-6995086-0      | ./1/Samp(53).vir                  | 03d4a997f31e24541719783f1cef401242a80754 |         0 | NULL  |
|  33 | Doc.Dropper.Agent-7006756-0      | ./1/Samp(71).vir                  | fd90f64e056668540e7907f499ce013abf0bc271 |         0 | NULL  |
|  34 | NULL                             | ./1/Samp(6).vir                   | 3cad5603c0f9e39cc840cacd2f19441829202db6 |         0 | NULL  |
|  35 | Doc.Dropper.Agent-6995084-0      | ./1/Samp(20).vir                  | 498a99c9f5f5551d4deba16c1905903e4c58b904 |         0 | NULL  |
|  36 | Doc.Dropper.Agent-6992012-0      | ./1/Samp(79).vir                  | 9fbbaa900864e6418c643e647d8b312a510a093d |         0 | NULL  |
|  37 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(40).vir                  | f5c01f42438dcf0f760d71ad984f228e3e3db6a1 |         0 | NULL  |
|  38 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(8).vir                   | 68b0d29242c598ac3756b48aaac5d7553ea6fbbd |         0 | NULL  |
|  39 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(9).vir                   | c528438e75ae5b8195f724005a725ba7007c580f |         0 | NULL  |
|  40 | Doc.Dropper.Agent-6995121-0      | ./1/Samp(67).vir                  | 5a99ac055bf26082631b1782c4433c317a748d09 |         0 | NULL  |
|  41 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(26).vir                  | 4bb607a102a1a8983e53d872292f70344c3ba238 |         0 | NULL  |
|  42 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(14).vir                  | 661409969c31c5bc8d3c1d5b057425db74118348 |         0 | NULL  |
|  43 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(17).vir                  | 7bdcf6a93e55002371acd4a285b6db9a70588359 |         0 | NULL  |
|  44 | NULL                             | ./1/Samp(75).vir                  | 8ef6d3932d01ec4625bce5b2568fa68e9f2c245e |         0 | NULL  |
|  45 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(101).vir                 | 74708f52ab4d2ed0c2406f2b4dbe88cb52706a85 |         0 | NULL  |
|  46 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(100).vir                 | e196ec570c539c670ff680bc4f8dda501f10805d |         0 | NULL  |
|  47 | NULL                             | ./1/Samp(32).vir                  | 2aa7372485831af4355f66f815017e5dcf2135ad |         0 | NULL  |
|  48 | Doc.Dropper.Agent-6995076-0      | ./1/Samp(21).vir                  | 5a9c0f23baeba576a0e315d06ef2cda0eb428c0c |         0 | NULL  |
|  49 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(25).vir                  | 441614e8a12031b5006f39eafc9f32424170fab8 |         0 | NULL  |
|  50 | Doc.Dropper.Agent-6995083-0      | ./1/Samp(88).vir                  | 230b38d87d8ce533bfdd5ef5180a7a6f0a5d7c4d |         0 | NULL  |
|  51 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(15).vir                  | 077f9e50df8dd733447c2d23b2052196db0bfe45 |         0 | NULL  |
|  52 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(103).vir                 | 60b13857d9ce197d3e93853472d82e1bf701b7fe |         0 | NULL  |
|  53 | NULL                             | ./1/Samp(64).vir                  | 91b6c0000d7747e259c6ef13447a33748c8a3adc |         0 | NULL  |
|  54 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(36).vir                  | 98b21f33f424cc3db21891de16bfec091c3bddd6 |         0 | NULL  |
|  55 | Doc.Dropper.Agent-6995166-0      | ./1/Samp(97).vir                  | 9fb64ee668eb41c3d108a79cc65c3989799dee8e |         0 | NULL  |
|  56 | Doc.Dropper.Agent-6995077-0      | ./1/Samp(73).vir                  | 3acab120eb9404a25c54804ae9f73358251ad181 |         0 | NULL  |
|  57 | Doc.Dropper.Agent-6995088-0      | ./1/Samp(42).vir                  | bfac9f7d82bac0cacbdeb3de47003bb2d47af119 |         0 | NULL  |
|  58 | Doc.Dropper.Agent-6995082-0      | ./1/Samp(5).vir                   | 14a4e87559f55b166c4a91191495611f82a32adc |         0 | NULL  |
|  59 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(48).vir                  | e61d8906ff53adeb0fa185f20b7f94cb3369c4d7 |         0 | NULL  |
|  60 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(18).vir                  | 9dc2238c9c49d8be2b71c965dfe89b46d3bb9440 |         0 | NULL  |
|  61 | Doc.Downloader.Jaff-6329915-0    | ./1/Samp(109).vir                 | f1957a07c3c3f3e62d4e645e5a8b71edd16f28da |         0 | NULL  |
|  62 | Doc.Dropper.Agent-6995078-0      | ./1/Samp(35).vir                  | 75d1094de9403cc0c385e45926b31cc055180731 |         0 | NULL  |
|  63 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(95).vir                  | ccf1591e8e04221e7284e44652199d0bdf97a807 |         0 | NULL  |
|  64 | NULL                             | ./1/Samp(98).vir                  | a903ed3ddf593c6f6ebf1a683db3e8659a1c94f6 |         0 | NULL  |
|  65 | Doc.Dropper.VBAgent-6879901-0    | ./1/Samp(43).vir                  | 8460fb72b66501e651b11d8fe33da30198657ea3 |         0 | NULL  |
|  66 | Doc.Dropper.Agent-6995080-0      | ./1/Samp(34).vir                  | cae7761ad91979803aeb134973bbde65b0286246 |         0 | NULL  |
|  67 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(65).vir                  | c897291852e7a9585b664de12372c82c5cf800fc |         0 | NULL  |
|  68 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(38).vir                  | c324700f1d91d8915ca9474c05667e47571f351d |         0 | NULL  |
|  69 | Doc.Dropper.Agent-6995118-0      | ./1/Samp(37).vir                  | 691477438d984bf76f5616b0c3ea9bd46c186b6b |         0 | NULL  |
|  70 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(81).vir                  | 642789bace2e7dfda112d42f24016b86025c4ede |         0 | NULL  |
|  71 | Doc.Dropper.Agent-7054319-0      | ./1/Samp(107).vir                 | b5b17886cf1a32087ca052bba37f8828bedc5046 |         0 | NULL  |
|  72 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(60).vir                  | 79ff6024c205ce87086d17ef9e65a1a5757c8072 |         0 | NULL  |
|  73 | Doc.Dropper.Agent-6995244-0      | ./1/Samp(16).vir                  | 6cb13d8ba85c6e53e8589475542f003d539eaffb |         0 | NULL  |
|  74 | Doc.Dropper.Agent-6995122-0      | ./1/Samp(41).vir                  | 7fa37dc079d2bd4680d69a9f302c04155601a88b |         0 | NULL  |
|  75 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(105).vir                 | 4900565974260e3f759420031ae1964606c4b349 |         0 | NULL  |
|  76 | Doc.Dropper.Agent-6995091-0      | ./1/Samp(58).vir                  | b3a22857affbbb025517abc9c732b8d3f7f71754 |         0 | NULL  |
|  77 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(52).vir                  | e9cf2c6df378b25224b00a314cbbada3ec0c21a0 |         0 | NULL  |
|  78 | Doc.Dropper.Agent-6995089-0      | ./1/Samp(12).vir                  | 2aacacf68b1b15c878c300816e804fda64445bdd |         0 | NULL  |
|  79 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(59).vir                  | 35d7411e70aaf0b9a48583fc3f35ba625850f304 |         0 | NULL  |
|  80 | Doc.Dropper.Agent-6995119-0      | ./1/Samp(86).vir                  | 06cdc840f023cb05db1e73e903cebe94568ca82d |         0 | NULL  |
|  81 | NULL                             | ./1/Samp(104).vir                 | acb634d23dff2d29958ec7d695652f66a6850290 |         0 | NULL  |
|  82 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(89).vir                  | f284127fc8c23c6955ce5453b7f1745c771a79d5 |         0 | NULL  |
|  83 | Doc.Dropper.Agent-6995124-0      | ./1/Samp(110).vir                 | 3a0b1883506f483fd01615f409e4e0be8e62d909 |         0 | NULL  |
|  84 | NULL                             | ./1/Samp(49).vir                  | 66a58743c519d98dc0fbb356322cf7d49f963e63 |         0 | NULL  |
|  85 | Doc.Dropper.Agent-6995075-0      | ./1/Samp(45).vir                  | 2ad853b427fa705d7223fe08a638dc45c394588b |         0 | NULL  |
|  86 | Doc.Dropper.Agent-6995164-0      | ./1/Samp(22).vir                  | 50f50ce9547d555da421cb57f5bdcbabff27cb91 |         0 | NULL  |
|  87 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(87).vir                  | 46fa1b5a7d501e9aa74c76776af1f65ee5a37c3e |         0 | NULL  |
|  88 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(31).vir                  | 94ab81cc6e73c9114162b4e45003cf08a07bcf0f |         0 | NULL  |
|  89 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(57).vir                  | f5a2e9d773cb00fbd9f540a92fb3fd810ae5340c |         0 | NULL  |
|  90 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(54).vir                  | 1ef68cee6440e39e70f72e356e7b993d59f4b077 |         0 | NULL  |
|  91 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(33).vir                  | 9723b0b4cdba96e317dacf410890dfddb6491940 |         0 | NULL  |
|  92 | NULL                             | ./1/Samp(1).vir                   | f342a08da414be3ff24db753e6e6db9b3a823816 |         0 | NULL  |
|  93 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(10).vir                  | 1a644a3f33019a9c2f70b9685e18b6f1d6a14a6c |         0 | NULL  |
|  94 | Doc.Dropper.Agent-6995167-0      | ./1/Samp(47).vir                  | 4991974b50d0991463778893fdded41b3e4f4ddb |         0 | NULL  |
|  95 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(102).vir                 | bbf0fe73a7a05dd9f054b5ce5850da223d7edcb8 |         0 | NULL  |
|  96 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(11).vir                  | fb3458e4d6105087b5717ee076be7425ef12040b |         0 | NULL  |
|  97 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(76).vir                  | 5d2440de579d497b745c779e7f83fcdf4fb4a152 |         0 | NULL  |
|  98 | Doc.Dropper.Agent-6995090-0      | ./1/Samp(84).vir                  | e941caaf89907fcb00d5f353debba759afaa4cff |         0 | NULL  |
|  99 | NULL                             | ./1/Samp(96).vir                  | aaccbfc3a9cab5d3a9bb6c50e8d793779d4280d9 |         0 | NULL  |
| 100 | Doc.Dropper.Agent-6995123-0      | ./1/Samp(83).vir                  | 7eb4018818bc235abd010986971f02d2565641ec |         0 | NULL  |
| 101 | NULL                             | ./1/viruss.rar                    | 8e3639a1d5326c79a151ef0242a8023b41c89f8c |         0 | NULL  |
| 102 | Doc.Dropper.VBAgent-6879901-0    | ./1/Samp(30).vir                  | a56d65b4cb2b8f489d162dd4246b81d1e4874bd8 |         0 | NULL  |
| 103 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(94).vir                  | d39324f5dd00d457707bb2b3c561155e6a87f50d |         0 | NULL  |
| 104 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(29).vir                  | f258a5ee14046468d621031528973bc17df8e1ef |         0 | NULL  |
| 105 | NULL                             | ./1/Samp(70).vir                  | 1abb2666dffb8997467b2845627831aa027bd615 |         0 | NULL  |
| 106 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(13).vir                  | 46af95857af961e33f58dedcda1c263b21bffc9f |         0 | NULL  |
| 107 | Doc.Dropper.Agent-6995115-0      | ./1/Samp(77).vir                  | 0b0cb772c47fbf5098dfcacfdd95bd78e7405b30 |         0 | NULL  |
| 108 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(66).vir                  | 3a94cfa795b5c224df6fb3c722d50694ec5bfccc |         0 | NULL  |
| 109 | NULL                             | ./1/Samp(4).vir                   | a274fe08a25cb1ff281374e7ff4da367b5b8c135 |         0 | NULL  |
| 110 | Doc.Downloader.Jaff-6329915-0    | ./1/Samp(106).vir                 | c09829a3fa9ec5967c3aaa348b4628cdbd174ea1 |         0 | NULL  |
| 111 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(91).vir                  | f60dcd0281ba5f023748f941803192eaa2ad3ca0 |         0 | NULL  |
| 112 | Doc.Dropper.Agent-6995079-0      | ./1/Samp(56).vir                  | 8ca462783605c3e6f9cd8bed8e46b9a57af31f7e |         0 | NULL  |
| 113 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(7).vir                   | 71a85ebf9c0eefca3c8f8ace766c33b9563e2109 |         0 | NULL  |
| 114 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(68).vir                  | 10a3de532f10d3fb80a1a9dd9cfc8f1708f03612 |         0 | NULL  |
| 115 | NULL                             | ./1/Samp(99).vir                  | b63a1cf15080977ba3174ed4c9eeeeecc0749f9b |         0 | NULL  |
| 116 | Doc.Dropper.Ursnif-6864686-0     | ./1/Samp(72).vir                  | e03d82497b3503113d6c8bbdeeb6d6da9ed12f1b |         0 | NULL  |
| 117 | Doc.Dropper.Agent-6995094-0      | ./1/Samp(51).vir                  | 4706145a5d61a4cce740dfd8f7b718cf46797151 |         0 | NULL  |
+-----+----------------------------------+-----------------------------------+------------------------------------------+-----------+-------+
`

Number Too little？ clamav  recognized the family, but it seems that  did not create a category.

I really like your open source project, learning the code you write, how to implement the function, very good

**Comment by joxeankoret** [comment]
Either the samples don't look related at Control Flow Graph level or there aren't enough samples. Actually, I have downloaded just the 3 first samples I found in your MySQL dump and, well, they aren't clustereable:

```
5b0d94cd3978ddc89fdfe70708799624a9be32741bbd9b9f00945248755f26e5: PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows
5d5a186e7976e3f7f982af94720070b78ed72fa1318a803722a6d823d5899c2d: Composite Document File V2 Document, Little Endian, Os: Windows, Version 10.0, Code page: 1251, Title: s2od3ds240ll93l6t048b2lthob9z4gxm, Subject: y4ikzz4d3zar9vnrm65i6zr56obtdau, Author: 6yql28pyn6xzg, Comments: 8dfqyjaed78vs0ppvisj1e89, Template: Normal, Last Saved By:  Windows, Revision Number: 11, Name of Creating Application: Microsoft Office Word, Total Editing Time: 03:00, Create Time/Date: Thu Apr 19 19:59:00 2018, Last Saved Time/Date: Thu May  2 10:13:00 2019, Number of Pages: 1, Number of Words: 1, Number of Characters: 7, Security: 0
80f3eaed3db756ffc4ef5cb757922129381faeeb28a9b25aafcc8e0da2ea294f: Composite Document File V2 Document, Little Endian, Os: Windows, Version 6.1, Code page: 1251, Template: Normal.dotm, Revision Number: 1, Name of Creating Application: Microsoft Office Word, Create Time/Date: Sun Mar 31 09:59:00 2019, Last Saved Time/Date: Sun Mar 31 09:59:00 2019, Number of Pages: 1, Number of Words: 0, Number of Characters: 5, Security: 0
```

Cosa Nostra only clusters executable files.

**Comment by TimelifeCzy** [comment]
> 
> 
> Either the samples don't look related at Control Flow Graph level or there aren't enough samples. Actually, I have downloaded just the 3 first samples I found in your MySQL dump and, well, they aren't clustereable:
> 
> ```
> 5b0d94cd3978ddc89fdfe70708799624a9be32741bbd9b9f00945248755f26e5: PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows
> 5d5a186e7976e3f7f982af94720070b78ed72fa1318a803722a6d823d5899c2d: Composite Document File V2 Document, Little Endian, Os: Windows, Version 10.0, Code page: 1251, Title: s2od3ds240ll93l6t048b2lthob9z4gxm, Subject: y4ikzz4d3zar9vnrm65i6zr56obtdau, Author: 6yql28pyn6xzg, Comments: 8dfqyjaed78vs0ppvisj1e89, Template: Normal, Last Saved By:  Windows, Revision Number: 11, Name of Creating Application: Microsoft Office Word, Total Editing Time: 03:00, Create Time/Date: Thu Apr 19 19:59:00 2018, Last Saved Time/Date: Thu May  2 10:13:00 2019, Number of Pages: 1, Number of Words: 1, Number of Characters: 7, Security: 0
> 80f3eaed3db756ffc4ef5cb757922129381faeeb28a9b25aafcc8e0da2ea294f: Composite Document File V2 Document, Little Endian, Os: Windows, Version 6.1, Code page: 1251, Template: Normal.dotm, Revision Number: 1, Name of Creating Application: Microsoft Office Word, Create Time/Date: Sun Mar 31 09:59:00 2019, Last Saved Time/Date: Sun Mar 31 09:59:00 2019, Number of Pages: 1, Number of Words: 0, Number of Characters: 5, Security: 0
> ```
> 
> Cosa Nostra only clusters executable files.

thank！
